spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STUDENT-MICROSERVICE
          uri: lb://STUDENT-MICROSERVICE
          predicates:
            - Path=/student/**
          filters:
          - name: CircuitBreaker
            args:
              name: STUDENT-MICROSERVICE
              fallbackuri: forward:/StudentFallback
          
        - id: COLLEGE-MICROSERVICE
          uri: lb://COLLEGE-MICROSERVICE
          predicates:
            - Path=/college/**
          filters:
          - name: CircuitBreaker
            args:
              name: COLLEGE-MICROSERVICE
              fallbackuri: forward:/collegeFallback
         
        - id: Feign-Client
          uri: lb://Feign-Client
          predicates:
            - Path=/feign/**
          filters:
          - name: CircuitBreaker
            args:
              name: Feign-Client
              fallbackuri: forward:/feignFallback  
              
        - id: STUDENT-MICROSERVICE
          uri: lb://STUDENT-MICROSERVICE
          predicates:
            - Path=/feignstudents/**
          filters:
          - name: CircuitBreaker
            args:
              name: STUDENT-MICROSERVICE
              fallbackuri: forward:/feignFallback        
         

server:
  port: 8989
management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 

